### ISSUE TITLE
Dialog-proceed-afterAllStep wrong place

### ISSUE THREAD

**Issue by dimaodnokoz** [koot-labs/telegram-bot-dialogs#17]
Hello. I'm very interested to use this package, so i explore it in details to understand it. As i'm new to github i have no experience in PRs and merging, so i decided to write here. Please, forgive for that.

I think there is a wrong place for 
```php
if ($this->isEnd()) {
    $this->afterAllStep($update);
    return;
}
```
in the beginning of proceed function in Dialog.php file. 

Imagine, you are at the last step of dialog. In Dialog:proceed $this->isEnd returns false, then all the things are done and dialog steps counter becomes +1 in the end of function. After that flow appears in DialogManager:proceed right before the code
```php
if ($dialog->isEnd()) {
    $this->forgetDialogState($dialog);
}
```
So this dialog will be deleted from Store here. So in this example afterAllStep didn't work at the beginning, because there was not the end of dialog. But it will never work later, because dialog was deleted. So i think in proceed function of Dialog.php the code 
```php
if ($this->isEnd()) {
    $this->afterAllStep($update);
    return;
}
```
should be transferred to the place right after 
```php
 ++$this->next;
```
in the end of file.

**Comment by alies-dev** [comment]
hey @dimaodnokoz 
It looks like a great catch!

Unfortunately, I can't check it. Can you please create a test that will catch this issue and then a PR to fix the problem? It will be a huge improvement for the package. thank you in advance!

**Comment by alies-dev** [comment]
UPD: BTW, I deprecated these methods and created the same but with less confusing names: https://github.com/koot-labs/telegram-bot-dialogs/commit/4b63fabd844c9fb6787be638ad1b8d31b828955d

**Comment by dimaodnokoz** [comment]
To make a test for this i need to use DialogManager instance, which needs Bot and Storage instances. I studied your Tests and understood how to build tests like that. But here is more complicated task and i can not manage it, because the way to create Store instance is still not clear for me. In Tests and in general. BTW you have no any tests for storing of dialogs data between requests. Only for storing data between steps, which is test of work with memory only. It seems it's important to have tests like that. And having at least one will help me to build more. I'm ready to help, but there are lot of things new to me, and i'm still failing my attempts in most cases.

**Comment by alies-dev** [comment]
>because the way to create Store instance is still not clear for me. 

In short, it's just `app('cache')->store('file')`. Instead of `file` you can use any other store from your `config/cache.php`

**Comment by dimaodnokoz** [comment]
Hello, @alies-dev. I made PR today. I made it two times. It seems it is shown as 1 PR, i hope it is ok. So the second PR was about this issue. My test proves my suppose. I may make PR with fix, but please, suggest me a process. As i understand, first you should approve my PR with test and check that it fails, right? Then i should make PR with fix and you will check it with test again, right?
