### ISSUE TITLE
generateDialogKeySharedBetweenUsers and generateDialogKeyUserBounded - wrong context in the functions names

### ISSUE THREAD

**Issue by dimaodnokoz** [koot-labs/telegram-bot-dialogs#18]
Hello. I'm very interested to use this package, so i explore it in details to understand it. As i'm new to github i have no experience in PRs and merging, so i decided to write here. Please, forgive for that.

You use 2 functions
1) generateDialogKeyUserBounded: this is will be used for example in dialogs in groups. Every user has the same chatId, but they all have different userIds. So you use both values to gen dialog key.
2) generateDialogKeySharedBetweenUsers: this is for user-bot dialogs, where there is only 1 user and bot. In this case userId=chatId in Update. And that's why you may use only chatId to gen dialog key.

But in 2) it's wrong to say that chatId is a key shared between users. All chatIds are different here, because each of them is equal to userId of proper user. Nothing shared here. As a result "user bounded" is more logical here, than in 1). I think both names are not good and lead to misunderstaning when reading code. Maybe it is better to use 
1) generatePersonalDialogKey
2) generateGroupDialogKey

**Comment by alies-dev** [comment]
Hey @dimaodnokoz 



I think I answered to this question here: https://github.com/koot-labs/telegram-bot-dialogs/issues/19#issuecomment-2106268638 . If I misunderstood something - please tell me. thank you!

**Comment by dimaodnokoz** [comment]
I replied in that stream. Probably it's better to close these one.

**Comment by alies-dev** [comment]
duplicate #19
