### ISSUE TITLE
Generate dialog key formula to have in one place

### ISSUE THREAD

**Issue by dimaodnokoz** [koot-labs/telegram-bot-dialogs#19]
Hello. I'm very interested to use this package, so i explore it in details to understand it. As i'm new to github i have no experience in PRs and merging, so i decided to write here. Please, forgive for that.

You use implode to generate dialog key more or less in the same way in 3 functions of DialogManager.php:
generateDialogKeyUserBounded
generateDialogKeySharedBetweenUsers
generateDialogKeySharedBetweenUsers

Maybe it will be better to have 1 place for this formula? I mean to add function, which generates key from 2 values. And then use it in all 3 functions. It will help to make changes to gen formula (for example replace - to |) in one place and do not loose something.

**Comment by alies-dev** [comment]
When you add a bot to a multiuser chat, there are 2 cases:
  1. when the bot should react to a single user messages
  1. when the bot should react to all users messages

That's why we have 2 ways to generate keys. In the first case the dialog is bounded to a single user. In 2nd - to any user.


in 1:1 charts with the bot, first case is the same as the second.

**Comment by dimaodnokoz** [comment]
I understand the idea of your naming, but it is not obvious at all. Especially when trying to understand the logic of findDialogKeyForStore function. I tried to find more "clear" names, but failed. As these 2 functions are private, we may stop our discussion here. But i'd like to describe my solution to my both questions about naming and formula.

The only place, where generateDialogKeyUserBounded and generateDialogKeySharedBetweenUsers are used is function findDialogKeyForStore. If the names are so unclear, probably it is better not to use them at all, and all logic place in findDialogKeyForStore with clear comments. It is about naming. As for formula, i just proposed to generate key in 1 function, not in 3. Here is the way i mean:

Clear description for variable in Dialog.php:

/** @var int|null id of the User the Dialog is bounded to.
Should be set only for multi-user chat dialogs, where bot should treat every user messages as separate dialog. */
protected ?int $user_id = null;

//======

Functions for DialogManager.php:

private function generateDialogKey($chatId, $userId = null): string
    {
        return implode('-', array_filter([
            $chatId,
            $userId,
        ]));
    }

//===

private function getDialogKey(Dialog $dialog): string
    {
        return $this->generateDialogKey(
            $dialog->getChatId(),
            $dialog->getUserId(),
        );
    }

//===

private function findDialogKeyForStore(Update $update): ?string
    {
         //As for 1-1 personal chat and multi-user chat, where bot should treat all users messages as one dialog 
        $chatBoundedDialogKey = $this->generateDialogKey($update->getChat()->id);
        if ($this->store->has($chatBoundedDialogKey)) {
            return $chatBoundedDialogKey;
        }

        //As for multi-user chat, where bot should treat every user messages as separate dialog
        $userBoundedDialogKey = $this->generateDialogKey($update->getChat()->id, $update->getMessage()->from->id);
        if ($this->store->has($userBoundedDialogKey)) {
            return $userBoundedDialogKey;
        }

        return null;
    }

**Comment by alies-dev** [comment]
since we are talking about private method names, let's close it. I'm open to improve names, but via PR flow :)
