### ISSUE TITLE
Dialog.php: add "get" from memory?

### ISSUE THREAD

**Issue by dimaodnokoz** [koot-labs/telegram-bot-dialogs#20]
Hello. I'm very interested to use this package, so i explore it in details to understand it. As i'm new to github i have no experience in PRs and merging, so i decided to write here. Please, forgive for that.

There are "remember" and "forget" functions for memory in Dialog.php. But there is no "get" function. Probably that's because the call of function (like $this->get($key)) is almost the same as to use memory directly (like $this->memory["$key"]), but there is one argument to use function. When $key doesn't exist in memory array, there will be exception. Maybe it is better to have "get" function, which will make key_exists check from beginning and return null, if there is no key. It seems more useful.

**Comment by alies-dev** [comment]
Agree, it will be nice to have a better DX to get something from var, like `$this->getFromMemory($key, $default)`. But it looks more verbose than `$this->memory[$key] ?? $default`, right? As an alternative, we can use:
```php
$this->memory($key)
```
but in this case we should not add 2nd param to avoid confusion between read and write operations.

**Comment by dimaodnokoz** [comment]
Thank you for traits. Now i know about this useful thing. Also thank you for your example of trait - it's worth to use even as example of dev with sdk.

I did not understand you direct answer to my question. As i wrote, $this->memory($key) will throw an exception, if there is no key. So it looks like it should be updated some way. As for me it is necessary, so it's not about some extra things in traits. As it is 1 line of code, it seems it's easy for you to add it, than to work with my PR. Maybe i still do not catch some idea about work with exceptions or something i don't know. Ok, maybe i will understand in practice.

**Comment by alies-dev** [comment]
Thanks for sharing your thought! 

I think the best what we can do it not to introduce a new API or methods, but use Laravel Collection instead of array:
`$this->memory = new Collection();`

The only problem—need to support dialogs created by previous versions of the package. For this, we need to implement a custom `__unserialize` method. What is still easy. I like this idea and I'll implement it this week

**Comment by alies-dev** [comment]
hey @dimaodnokoz 
I created PR #23 , is that what are you looking for?
