### ISSUE TITLE
Use Dialog in group has bug

### ISSUE THREAD

**Issue by CrazyBoy49z** [koot-labs/telegram-bot-dialogs#4]
### PHP version

8.1.5

### Package version

0.5.2

### Laravel version (if any)

9.52.5

### Code To Reproduce the bug

If you use it in group chats, other users can intercept the dialogue. I think it would be more correct to analyze chat id + user id
 

### Error stacktrace (if any)

<img width="840" alt="Знімок екрана 2023-04-18 о 19 26 38" src="https://user-images.githubusercontent.com/3448603/232842920-9deccefb-9fed-4921-8b9a-bffdb720c76d.png">

**Comment by alies-dev** [comment]
Hey @CrazyBoy49z 

thank you for using this package.

Unfortunately, I don't use it anymore, but open for PRs.
This package was developed to support private dialogs. But we can consider supporting, feel free to open a PR

**Comment by CrazyBoy49z** [comment]
@alies-dev My solution will unfortunately break backwards compatibility

**Comment by alies-dev** [comment]
@CrazyBoy49z 
that's sort of ok, the package has not achieved version 1.0 yet.

**Comment by dimaodnokoz** [comment]
@alies-dev, hello. As you mentioned above you do not use this package anymore. Is it ok if i copy your package (not fork), will develop and maintain it independantly on my own? I'm new to github and want to feel protected from unexpected mistakes from different syncs i do not understand yet. I also try to make it as simple as possible for me to start here. Of course i will add info about you and your package as a first source to my description and will keep it there. Or please advice me something about all that.

**Comment by alies-dev** [comment]
hey @dimaodnokoz 

Yes, for sure, please just follow MIT license guidelines. Note, "I don't use the package" doesn't mean it's not maintained anymore: I like the problem this package solves and would love to find an elegant solution for it. So, I'm going to maintain this package and have some ideas how to improve it for v1.0
